name: eralpsoftware
description: Bu paket EralpSoftware'nin resmi açık kaynak kütüphanesidir. İçerisinde şirkette kullandığımız widget'ler ve helper'ler yer almaktadır.
version: 0.0.91
authors:
  - Cem Ergin <cem.ergin@eralpsoftware.com>
  - Burak Can Kurtarır <burak.kurtarir@eralpsoftware.com>
homepage: https://github.com/eralpsoftware/flutter_eralpsoftware

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
